name: keyboard_shortcuts
description: Widget that allow you to use shortcuts for your application. Custom shortcuts that you define by yourself and global like auto scroll to bottom and top.
version: 0.1.5
publish_to: none
homepage: https://github.com/AntoineMarcel/keyboard_shortcuts

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  visibility_detector: ^0.3.3
  tuple: ^2.0.0
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  flutter_test:
    sdk: flutter